# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-10 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='congregation_id',
            field=models.IntegerField(),
        ),
    ]
