# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-10 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metro', '0002_auto_20170510_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='congregation_id',
            field=models.IntegerField(null=True),
        ),
    ]
